# 전체 읽혀짐
#servers:
#  - dev.bar.com
#  - foo.bar.com

# Local 읽혀짐

kdt:
  version: "default-v1.0"
  minimum-order-amount: 1
  supportVendors:
    - defulat
  description: |-
    defulat line 1  hello world
    defulat line 2 xxxx
    defulat line 3
